### PR TITLE
Build rubies for heroku-18

### PR DESCRIPTION
**Pull request by dmathieu**
cc @schneems @hone

### CODE REVIEW

**Comment by dmathieu** [comment]
I have built, uploaded and tested this works.

**Comment by dmathieu** [comment]
I've built and pushed 2.4.4.
I'm getting openssl errors for 2.3.7 though. @hone, is there something different to be done for it?

**Comment by schneems** [comment]
I'm unable to build any versions of 2.3. I think we'll likely drop support for it for Heroku-18, unfortunately it means we need to do work to ship 2.4 as the default Ruby version, which is non-trivial, i'm working on it over here https://github.com/heroku/heroku-buildpack-ruby/pull/734

**Comment by schneems** [comment]
Closing via https://github.com/hone/docker-heroku-ruby-builder/commit/9024945611725585539437da7c47b7b2f3acf92b

**Pull request closed without merging**
